server:
  port: 8080

spring:
  cloud:
    function:
      definition: invoice;
    stream:
      bindings:
        invoice-out-0:
          destination: invoice.topic
          producer:
            useNativeEncoding: true
      kafka:
        bindings:
          invoice-out-0:
            producer:
              configuration:
                value:
                  serializer: com.jfjara.kafkaproducer.invoice.infrastructure.kafka.serializer.InvoiceSerializer
        binder:
          brokers: localhost:9092
